services:
  RSI-Batch:
#    build:
#      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    networks:
      - RSI-network
    image: weseeonggu/rsibatch:latest
networks:
  RSI-network:
    driver: bridge