name: Deploy to Self-hosted Server

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: self-hosted  # 배포할 PC에서 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: |
          ./gradlew build  -x test

      - name: Restart Application
        run: |
          pkill -f "my-app.jar" || true 
          nohup java -jar build/libs/my-app.jar > app.log 2>&1 &
